#pragma once

#define TO_DEG *180/M_PI
#define TO_RAD *M_PI/180

/// Errors strings
#define ERROR_PLL "PLL ERROR: "
#define ERROR_PHASE "PHASE PROCESSOR ERROR: "
#define ERROR_GEN "SIGNAL GENERATOR ERROR: "
#define ERROR_PLOT "PLOT MAKER ERROR: "
#define ERROR_MAG_MODULATOR "MAGNITUDE MODULATOR ERROR: "
#define ERROR_BPSK_MODUlATOR "BPSK MODULATOR ERROR: "
#define ERROR_CAST "CAST ERRROR: "
